name: Create and publish a Docker image

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:  # Enable manual triggering
    inputs:
      tag:
        description: 'Docker image tag'
        required: false

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Docker image tag
        id: set_docker_tag
        run: echo "tag=${{ github.event.inputs.tag || github.ref_name }}" >> $GITHUB_OUTPUT
        continue-on-error: true
        shell: bash
      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/typositoire/concourse-helm3-resource:${{ steps.set_docker_tag.outputs.tag }}
            ghcr.io/typositoire/concourse-helm3-resource:latest